name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: khaled-mohey10
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload generated SVGs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake-graph
          path: dist/
